name: ose_project_sven_jacobs

channels:
  - conda-forge

dependencies:
  - r-base=4.1.0
  
  - r-irkernel=1.2
  - notebook=6.4.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyterlab=3.0.16
  - nb_conda_kernels=2.3.1

  - r-tidyverse=1.3.1
  - r-ggpubr=0.4.0
  - r-stargazer=5.2.2
  - r-estimatr=0.30.2
  - r-qpcr=1.4_1
  - r-aer=1.2_9
